name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release:
        description: 'Create Release'
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches
    
    - name: Set Version
      shell: bash
      run: |
        TAGFS_VERSION=$(git describe --tags --always --dirty)
        echo "TAGFS_VERSION=${TAGFS_VERSION}" >> $GITHUB_ENV
    
    - name: Install Dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_TESTS=ON
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
      
    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest --output-on-failure -C Release
      
    - name: Test Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          ./Release/tagfs-hello.exe
        else
          ./tagfs-hello
        fi
        echo "Build artifact created for commit: ${GITHUB_SHA::8}"

    - name: Create Release Tag
      if: github.event_name == 'workflow_dispatch' && inputs.release && matrix.os == 'ubuntu-latest'
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        if ! git rev-parse "${TAGFS_VERSION}" >/dev/null 2>&1; then
          git tag -a "${TAGFS_VERSION}" -m "Release version ${TAGFS_VERSION}"
          git push origin "${TAGFS_VERSION}"
        else
          echo "Tag ${TAGFS_VERSION} already exists"
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}