name: Release

on:
  workflow_dispatch:
    inputs:
      draft:
        description: 'Create as draft release'
        type: boolean
        default: true
        required: false

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Version
        id: version
        shell: bash
        run: |
          VERSION=$(cat VERSION | tr -d '\n')
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT

      # Copy the build steps from ci.yml
      - name: Install Dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential
      
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DBUILD_TESTS=ON
      
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release
      
      - name: Run Tests
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest --output-on-failure -C Release

      - name: Create Artifact Name
        id: artifact
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "name=tagfs-${{ steps.version.outputs.version }}-windows.exe" >> $GITHUB_OUTPUT
            echo "path=build/Release/tagfs-hello.exe" >> $GITHUB_OUTPUT
          else
            echo "name=tagfs-${{ steps.version.outputs.version }}-${{ runner.os }}" >> $GITHUB_OUTPUT
            echo "path=build/tagfs-hello" >> $GITHUB_OUTPUT
          fi

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact.outputs.name }}
          path: ${{ steps.artifact.outputs.path }}

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Get Version
        id: version
        shell: bash
        run: |
          VERSION=$(cat VERSION | tr -d '\n')
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          draft: ${{ inputs.draft }}
          generate_release_notes: true
          files: artifacts/**/*